# coding: utf-8

"""
    Picarto.TV API Documentation

    The Picarto.TV API documentation  Note, for fixed access tokens, the header that needs to be sent is of the format: `Authorization: Bearer yourTokenHere`  This can be generated at https://oauth.picarto.tv/  For chat API, see https://docs.picarto.tv/chat/chat.proto - contact via the email below for implementation details 

    OpenAPI spec version: 1.2.5
    Contact: api@picarto.tv
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
import re


class UserEmailSettings(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'newsletter': 'bool',
        'live': 'bool',
        'follow': 'bool'
    }

    attribute_map = {
        'newsletter': 'newsletter',
        'live': 'live',
        'follow': 'follow'
    }

    def __init__(self, newsletter=None, live=None, follow=None):
        """
        UserEmailSettings - a model defined in Swagger
        """

        self._newsletter = None
        self._live = None
        self._follow = None

        if newsletter is not None:
          self.newsletter = newsletter
        if live is not None:
          self.live = live
        if follow is not None:
          self.follow = follow

    @property
    def newsletter(self):
        """
        Gets the newsletter of this UserEmailSettings.
        Newsletters

        :return: The newsletter of this UserEmailSettings.
        :rtype: bool
        """
        return self._newsletter

    @newsletter.setter
    def newsletter(self, newsletter):
        """
        Sets the newsletter of this UserEmailSettings.
        Newsletters

        :param newsletter: The newsletter of this UserEmailSettings.
        :type: bool
        """

        self._newsletter = newsletter

    @property
    def live(self):
        """
        Gets the live of this UserEmailSettings.
        Live notifications

        :return: The live of this UserEmailSettings.
        :rtype: bool
        """
        return self._live

    @live.setter
    def live(self, live):
        """
        Sets the live of this UserEmailSettings.
        Live notifications

        :param live: The live of this UserEmailSettings.
        :type: bool
        """

        self._live = live

    @property
    def follow(self):
        """
        Gets the follow of this UserEmailSettings.
        Follow notifications

        :return: The follow of this UserEmailSettings.
        :rtype: bool
        """
        return self._follow

    @follow.setter
    def follow(self, follow):
        """
        Sets the follow of this UserEmailSettings.
        Follow notifications

        :param follow: The follow of this UserEmailSettings.
        :type: bool
        """

        self._follow = follow

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in self.swagger_types.iteritems():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, UserEmailSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
